name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
      ref: master
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.dsi-config
      ref: main

trigger:
  branches:
    exclude:
    - master
    - develop
    - release/*
    - feature/*

variables:
- group: platform-global

stages:
- template: /Application/node/stages/signin-master-standalone-stage.yml@devopsTemplates
  parameters:
    applicationName: support
    resourceGroupSuffix: sup